### ISSUE TITLE
issue :: logs

### ISSUE THREAD

**Issue by prayagupa** [prayagupd/database-entertainment#1]
Public Key Retrieval is not allowed
------------------------------------

```
chat-backend    | 03:21:09.802 [scala-execution-context-global-15] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to create/setup connection: Public Key Retrieval is not allowed
chat-backend    | 03:21:09.804 [scala-execution-context-global-15] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Cannot acquire connection from data source
chat-backend    | java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:108)
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
chat-backend    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
chat-backend    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
chat-backend    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
chat-backend    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
chat-backend    | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
chat-backend    | 	at com.duwamish.chat.database.ConnectionPool$.<init>(ConnectionPool.scala:20)
chat-backend    | 	at com.duwamish.chat.database.ConnectionPool$.<clinit>(ConnectionPool.scala)
chat-backend    | 	at com.duwamish.chat.handlers.HandoffConfigHandler.$anonfun$getAllHandoffConfigs$1(HandoffConfigHandler.scala:77)
chat-backend    | 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
chat-backend    | 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
chat-backend    | 	at scala.util.Success.map(Try.scala:209)
chat-backend    | 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
chat-backend    | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
chat-backend    | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
chat-backend    | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
chat-backend    | 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
chat-backend    | 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
chat-backend    | 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
chat-backend    | 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
chat-backend    | 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
chat-backend    | 03:21:10.805 [scala-execution-context-global-15] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
chat-backend    | java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:108)
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
chat-backend    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
chat-backend    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
chat-backend    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
chat-backend    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
chat-backend    | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
chat-backend    | 	at com.duwamish.chat.database.ConnectionPool$.<init>(ConnectionPool.scala:20)
chat-backend    | 	at com.duwamish.chat.database.ConnectionPool$.<clinit>(ConnectionPool.scala)
chat-backend    | 	at com.duwamish.chat.handlers.HandoffConfigHandler.$anonfun$getAllHandoffConfigs$1(HandoffConfigHandler.scala:77)
chat-backend    | 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
chat-backend    | 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
chat-backend    | 	at scala.util.Success.map(Try.scala:209)
chat-backend    | 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
chat-backend    | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
chat-backend    | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
chat-backend    | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
chat-backend    | 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
chat-backend    | 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
chat-backend    | 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
chat-backend    | 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
chat-backend    | 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
chat-backend    | java.lang.ExceptionInInitializerError
chat-backend    | 	at com.duwamish.chat.handlers.HandoffConfigHandler.$anonfun$getAllHandoffConfigs$1(HandoffConfigHandler.scala:77)
chat-backend    | 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
chat-backend    | 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
chat-backend    | 	at scala.util.Success.map(Try.scala:209)
chat-backend    | 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
chat-backend    | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
chat-backend    | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
chat-backend    | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
chat-backend    | 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
chat-backend    | 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
chat-backend    | 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
chat-backend    | 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
chat-backend    | 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
chat-backend    | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Public Key Retrieval is not allowed
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:576)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
chat-backend    | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
chat-backend    | 	at com.duwamish.chat.database.ConnectionPool$.<init>(ConnectionPool.scala:20)
chat-backend    | 	at com.duwamish.chat.database.ConnectionPool$.<clinit>(ConnectionPool.scala)
chat-backend    | 	... 13 more
chat-backend    | Caused by: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:108)
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
chat-backend    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
chat-backend    | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
chat-backend    | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
chat-backend    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
chat-backend    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
chat-backend    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
chat-backend    | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
chat-backend    | 	... 17 more
```

fix: https://mysql-net.github.io/MySqlConnector/connection-options/

```
"jdbc:mysql://chat-server-mysql_compose:3306/chat?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
```

**Comment by prayagupa** [comment]
starting docker container

```
$ docker-compose up oracledb
Removing database-perf_oracledb_1
Recreating 60b0060c2fe7_database-perf_oracledb_1 ... done
Attaching to database-perf_oracledb_1
oracledb_1  | ln: failed to create symbolic link '/u01/app/oracle/product': Permission denied
database-perf_oracledb_1 exited with code 1
```

**Comment by prayagupa** [comment]
```
curl -O http://get.enterprisedb.com/postgresql/postgresql-12.9-1-osx-binaries.zip --output-dir /tmp/


unzip /tmp/postgresql-12.9-1-osx-binaries.zip -d /tmp/postgres/

-- 
var edb = EmbeddedPostgres
  .builder()
  .setPgDirectoryResolver(__ -> new File("/tmp/postgres/pgsql/"))
  .start();

```

```
-- Create a group
CREATE ROLE readaccess;

-- Grant access to existing tables
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;

-- Grant access to future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readaccess;

-- Create a final user with password
CREATE USER pg_rw WITH PASSWORD 'secret';
GRANT readaccess TO pg_rw;

--https://gist.github.com/oinopion/4a207726edba8b99fd0be31cb28124d0
```
